### ISSUE TITLE
使用shiki来取代highlight.js来进行代码的高亮

### ISSUE THREAD

**Issue by zyhnbyyds** [pd4d10/bytemd#34]
```ts
/**
 * ByteMD plugin to show the code block with shiki
 * @param options The options for shiki
 */
export function shikiPlugin(options?: CodeToHastOptions): BytemdPlugin {
  return {
    viewerEffect({ markdownBody }) {
      const els = markdownBody.querySelectorAll<HTMLElement>('pre>code')
      if (els.length === 0)
        return
      els.forEach(async (el) => {
        const lang = el.className.replace('language-', '')
        el.className = `${el.className} shiki-code`
        const codeGet = el.textContent || ''
        const code = await codeToHtml(codeGet, useAssign(options, {
          lang,
          themes: {
            light: 'github-light',
            dark: 'github-dark',
          },
        }))

        if (el.parentElement)
          el.parentElement.innerHTML = code
      },
      )
    },
  }
}
```

这个是插件的定义方式，我这边使用正常。这个实现非常的简单，希望官方可以作为参考，另外它的深色模式需要选举定义一下css样式来覆盖

```css
html.dark .shiki,
html.dark .shiki span {
  color: var(--shiki-dark) !important;
  background-color: var(--shiki-dark-bg) !important;
  font-style: var(--shiki-dark-font-style) !important;
  font-weight: var(--shiki-dark-font-weight) !important;
  text-decoration: var(--shiki-dark-text-decoration) !important;
}
```

如果需要我提供pr实现的话，我很乐意去做🫡。
