### ISSUE TITLE
Where is the dark theme located?

### ISSUE THREAD

**Issue by csuwildcat** [pd4d10/bytemd#4]
The demo on the playground page displays the preview with a dark theme, and I was wondering where that might be located so I can use it in my own instance.

**Comment by hookind** [comment]
同样求问。

目前只发现可通过下面语句覆盖样式，不太方便。

```css
:deep(.markdown-body) {
  background-color: #fff !important;
  color: #000 !important;
}
```
